name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      ydb:
        image: ydbplatform/local-ydb:latest
        env:
          GRPC_TLS_PORT: "2135"
          GRPC_PORT: "2136"
          MON_PORT: "8765"
          YDB_USE_IN_MEMORY_PDISKS: "true"
        ports:
          - "2135:2135"
          - "2136:2136"
          - "8765:8765"

    container: golang:1.23.1-bookworm

    steps:
      # installing/updating deps because steps are running inside container
      # https://github.com/actions/checkout/issues/363
      - name: install deps
        run: |
          apt-get update
          apt-get install -y git bc
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: install deps
        run: go mod download

      - name: run tests
        env:
          YDB_TEST_ENDPOINT: ydb:2136
          YDB_SERVERLESS_DB: ${{ secrets.YDB_SERVERLESS_DB }}
          YDB_SERVERLESS_IAM_KEY: ${{ secrets.YDB_SERVERLESS_IAM_KEY }}

        run: |
          go test -v -race -count=1 -cover -coverpkg=./... -coverprofile=profile.cov ./... -tags integration

          go tool cover -func=profile.cov -o=coverage.out
          go tool cover -html=profile.cov -o=coverage.html

      - name: coverage
        if: github.ref == 'refs/heads/main'
        id: coverage
        run: |
          cov=$(grep "total:"  coverage.out | awk '{print $3+0}')
          echo "coverage=$cov" >> $GITHUB_OUTPUT
          color=brightgreen
          if [ $(echo "$cov<=30"|bc) -eq 1 ]; then
            color=red
          elif [ $(echo "$cov<=70"|bc) -eq 1 ]; then
            color=yellow
          fi
          curl -s "https://img.shields.io/badge/Coverage-${cov}%25-${color}" --output coverage.svg

      - name: push info
        if: github.ref == 'refs/heads/main'
        run: |
          cov=${{ steps.coverage.outputs.coverage }}
          git config --local user.email "adwski@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git fetch --depth=1
          git checkout pages
          mkdir -p badges
          mkdir -p coverage
          echo $cov > coverage/percent
          if ! git diff --exit-code 1>/dev/null ; then
            cp coverage.svg badges/
            cp coverage.html coverage/
            git add badges/ coverage/
            git commit -m "update coverage [skip ci]"
            git push origin pages
          else
            echo "coverage did not change"
          fi
